$ANSIBLE_VAULT;1.1;AES256
37383030376335633237346633326330333035663061383764303364386561303465633266313735
3334613462346566376563613135623235626632626665660a333735386533393536396135643266
33313138343161393133343232323266313330613230306262613937366562646133373532306365
6530386135353439340a356465356432623438323936306436356237616464396138663836393335
63646464303839626435353139383230316562303863666230643638313861653837623935306435
63326334363239363831623438623961383365383063643331623837373765303237396139306266
38383364643334616565373635613964666634663438393165313934646631386337363065366131
61353437383032376331
